// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ESP32S3Watch

#include "ui.h"
#include "ui_helpers.h"
#include <stdio.h> 

///////////////////// VARIABLES ////////////////////
lv_anim_t * BackgroundPicAni_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_SplashScreen
void ui_SplashScreen_screen_init(void);
void ui_SplashScreen_screen_destroy(void);
void ui_event_SplashScreen(lv_event_t * e);
lv_obj_t * ui_SplashScreen;
lv_obj_t * ui_BackgroundPic;
lv_obj_t * ui_logo;
void anim_end_cb(lv_anim_t * anim);

//SCREEN : ui_HomeScreen
void ui_HomeScreen_screen_init(void);
void ui_HomeScreen_screen_destroy(void);
void ui_event_HomeScreen(lv_event_t * e);
lv_obj_t * ui_HomeScreen = NULL;
lv_obj_t * ui_HomeBackground = NULL;
lv_obj_t * ui_MinuteHands = NULL;
lv_obj_t * ui_Hourshands = NULL;
lv_obj_t * ui_SecondHand = NULL;
lv_obj_t * ui_AmPm;
// SCREEN: ui_HomeScreen2
void ui_HomeScreen2_screen_init(void);
void ui_HomeScreen2_screen_destroy(void);
void ui_event_HomeScreen2(lv_event_t * e);
lv_obj_t * ui_HomeScreen2 = NULL;
lv_obj_t * ui_HomeBackground2 = NULL;
lv_obj_t * ui_Hourshands2 = NULL;
lv_obj_t * ui_MinuteHands2 = NULL;
lv_obj_t * ui_SecondHand1 = NULL;
lv_obj_t * ui_AmPm2;

// SCREEN: ui_AlarmClockScreen
void ui_AlarmClockScreen_screen_init(void);
void ui_AlarmClockScreen_screen_destroy(void);
void ui_event_AlarmClockScreen(lv_event_t * e);
lv_obj_t * ui_AlarmClockScreen = NULL;
lv_obj_t * ui_AlarmClockLab = NULL;
lv_obj_t * ui_HourAlarm = NULL;
lv_obj_t * ui_MinuteAlarm = NULL;
lv_obj_t * ui_HourAlarmLab = NULL;
lv_obj_t * ui_MinuteAlarmLab = NULL;
lv_obj_t * ui_AlarmClockSwitch = NULL;
lv_obj_t * ui_AlarmClockSwitchLab = NULL;

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
lv_obj_t *ui_Screen5;
void ui_event_Screen5( lv_event_t * e);
lv_obj_t *ui_Image1;
lv_obj_t *ui_Label1;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
lv_anim_t * BackgroundPicAni_Animation(lv_obj_t * TargetObject, int delay)
{
    lv_anim_t * out_anim;
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 3000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, 3600);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle);
    lv_anim_set_ready_cb(&PropertyAnimation_0, anim_end_cb);
    out_anim = lv_anim_start(&PropertyAnimation_0);

    return out_anim;
}

void anim_end_cb(lv_anim_t * anim)
{
    _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_HomeScreen_screen_init);
}
///////////////////// FUNCTIONS ////////////////////
void send_event(void) {
  lv_event_send(ui_HomeScreen, LV_EVENT_REFRESH, NULL);
}

void ui_event_Screen5( lv_event_t * e)  {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t * target = lv_event_get_target(e);
  if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
    if(lvgl_port_lock(0)) {
      lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 0, 0, &ui_HomeScreen_screen_init);
      lv_obj_clear_state(ui_AlarmClockSwitch, LV_STATE_CHECKED);
      lvgl_port_unlock();
    }
    Screen_flag = 2;
    switchState = false;
    
  }
  if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
    if(lvgl_port_lock(0)) {
      lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 0, 0, &ui_HomeScreen_screen_init);
      lv_obj_clear_state(ui_AlarmClockSwitch, LV_STATE_CHECKED);;
      lvgl_port_unlock();
    }
    Screen_flag = 2;
    switchState = false;
    
  }
  if (event_code == LV_EVENT_CLICKED && lv_indev_get_type(lv_indev_get_act()) == LV_INDEV_TYPE_POINTER) {
    if(lvgl_port_lock(0)) {
      _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 0, 0, &ui_HomeScreen_screen_init);
      lv_obj_clear_state(ui_AlarmClockSwitch, LV_STATE_CHECKED);;
      lv_obj_clear_state(ui_AlarmClockSwitch, LV_STATE_CHECKED);
      lvgl_port_unlock();
    }
    Screen_flag = 2;
    switchState = false;
  }
}

void ui_event_SplashScreen(lv_event_t * e)
{

  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t * target = lv_event_get_target(e);
  if (event_code == LV_EVENT_SCREEN_LOADED) {
    BackgroundPicAni_Animation(ui_BackgroundPic, 0);
  }
}

void ui_event_HomeScreen(lv_event_t * e)
{
  lv_event_code_t event_code = lv_event_get_code(e);  
  lv_obj_t * target = lv_event_get_target(e);
  if (event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
      if(lvgl_port_lock(0)) {
          lv_indev_wait_release(lv_indev_get_act());
          _ui_screen_change(&ui_HomeScreen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 390, 0, &ui_HomeScreen2_screen_init);
          lvgl_port_unlock();
      }
    Screen_flag = 3;

  }
  if (event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
    if(lvgl_port_lock(0)) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_AlarmClockScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 390, 0, &ui_AlarmClockScreen_screen_init);
        lvgl_port_unlock();
    }
    Screen_flag = 4;
  }
  if ( event_code == LV_EVENT_SCREEN_LOADED) {
    //      time_s_Animation(ui_shand, 0);
  }
}

void ui_event_HomeScreen2(lv_event_t * e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t * target = lv_event_get_target(e);
  if (event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
    if(lvgl_port_lock(0)) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_AlarmClockScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 390, 0, &ui_AlarmClockScreen_screen_init);
        lvgl_port_unlock();
      }
    Screen_flag = 4;
  }
  if (event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
    if(lvgl_port_lock(0)) {
      lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 390, 0, &ui_HomeScreen_screen_init);
      lvgl_port_unlock();
    }
    Screen_flag = 2;
  }
  if ( event_code == LV_EVENT_SCREEN_LOADED) {
    //      time_s_Animation(ui_shand2, 0);
  }
}

void ui_event_AlarmClockScreen(lv_event_t * e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t * target = lv_event_get_target(e);
  if (event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
    if(lvgl_port_lock(0)) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 390, 0, &ui_HomeScreen_screen_init);
        lvgl_port_unlock();
      }
    Screen_flag = 2;
  }
  if (event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
    if(lvgl_port_lock(0)) {
      lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change(&ui_HomeScreen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 390, 0, &ui_HomeScreen2_screen_init);
      lvgl_port_unlock();
    
    }
    Screen_flag = 3;

  }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_SplashScreen_screen_init();
    ui_HomeScreen_screen_init();
    ui_HomeScreen2_screen_init();
    ui_testscreen_screen_init();
    ui_Screen5_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_SplashScreen);
}

void ui_destroy(void)
{
    ui_SplashScreen_screen_destroy();
    ui_HomeScreen_screen_destroy();
}

uint8_t hour = 0;
uint8_t minute = 0;
uint8_t second = 0;
uint32_t s = 0;
uint32_t tmp1 = 0;
uint32_t Screen_flag = 0;
//刷新时针位置
void time_refresh(lv_timer_t * timer) {
    s += 6;
    lv_img_set_angle(ui_SecondHand, s % 3600);
    lv_img_set_angle(ui_SecondHand1, s % 3600);
    
    if (s == 3600) {
        s = 0;
        tmp1 = 1;
    }
}
