// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ESP32S3Watch

#ifndef _ESP32S3WATCH_UI_H
#define _ESP32S3WATCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "Arduino.h"
///////////////////// SCREENS ////////////////////

//#include "ui_SplashScreen.h"
#include "ui_HomeScreen.h"

///////////////////// VARIABLES ////////////////////

lv_anim_t * BackgroundPicAni_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_SplashScreen
void ui_SplashScreen_screen_init(void);
void ui_SplashScreen_screen_destroy(void);
void ui_event_SplashScreen(lv_event_t * e);
extern lv_obj_t * ui_SplashScreen;
extern lv_obj_t * ui_BackgroundPic;
extern lv_obj_t * ui_logo;
void anim_end_cb(lv_anim_t * anim);

// SCREEN: ui_HomeScreen
extern void ui_HomeScreen_screen_init(void);
extern void ui_HomeScreen_screen_destroy(void);
void ui_event_HomeScreen(lv_event_t * e);
extern lv_obj_t * ui_HomeScreen;
extern lv_obj_t * ui_HomeBackground;
extern lv_obj_t * ui_MinuteHands;
extern lv_obj_t * ui_Hourshands;
extern lv_obj_t * ui_SecondHand;
extern lv_obj_t * ui_AmPm;
// SCREEN: ui_HomeScreen2
extern void ui_HomeScreen2_screen_init(void);
extern void ui_HomeScreen2_screen_destroy(void);
void ui_event_HomeScreen2(lv_event_t * e);
extern lv_obj_t * ui_HomeScreen2;
extern lv_obj_t * ui_HomeBackground2;
extern lv_obj_t * ui_Hourshands2;
extern lv_obj_t * ui_MinuteHands2;
extern lv_obj_t * ui_SecondHand1;
extern lv_obj_t * ui_AmPm2;
// SCREEN: ui_AlarmClockScreen
void ui_AlarmClockScreen_screen_init(void);
void ui_AlarmClockScreen_screen_destroy(void);
void ui_event_AlarmClockScreen(lv_event_t * e);
extern lv_obj_t * ui_AlarmClockScreen;
extern lv_obj_t * ui_AlarmClockLab;
extern lv_obj_t * ui_HourAlarm;
extern lv_obj_t * ui_MinuteAlarm;
extern lv_obj_t * ui_HourAlarmLab;
extern lv_obj_t * ui_MinuteAlarmLab;
extern lv_obj_t * ui_AlarmClockSwitch;
extern lv_obj_t * ui_AlarmClockSwitchLab;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t *ui_Screen5;
void ui_event_Screen5( lv_event_t * e);
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Label1;

void ui_testscreen_screen_init(void);
void ui_testscreen_screen_destroy(void);
extern lv_obj_t * ui_testscreen;
// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bj_02_png);    // assets/bj_02.png
LV_IMG_DECLARE(ui_img_1689836819);    // assets/elecrow_logo_600x600 拷贝.png
LV_IMG_DECLARE(ui_img_940840019);    // assets/表盘-01.png
LV_IMG_DECLARE(ui_img_65333621);    // assets/分针-01.png
LV_IMG_DECLARE(ui_img_1547215259);    // assets/时针-01.png
LV_IMG_DECLARE(ui_img_1290532093);    // assets/秒针-1.png
LV_IMG_DECLARE(ui_img_1668922148);    // assets/表盘-02.png
LV_IMG_DECLARE(ui_img_1666022858);    // assets/时针-02.png
LV_IMG_DECLARE(ui_img_1016395558);    // assets/分针-02.png
LV_IMG_DECLARE(ui_img_1290539516);    // assets/秒针-2.png
LV_IMG_DECLARE(ui_img_01_png); 


// Global variables are used to store switch states
extern bool switchState;
extern char  AlarmClockhour[32];
extern char  AlarmClockmimu[32];

//current time
extern uint8_t hour;
extern uint8_t minute;
extern uint8_t second;
extern uint32_t s;
extern uint32_t tmp1;
extern uint32_t Screen_flag;
void time_refresh(lv_timer_t *timer);
void send_event(void);\
extern bool anim_loaded_end;
extern int fal;

// UI INIT
void ui_init(void);
void ui_destroy(void);
extern void lvgl_port_unlock(void);
extern bool lvgl_port_lock(uint32_t timeout_ms);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
