// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ESP32S3Watch

#include "ui.h"


// event funtions
bool switchState = false;
char  AlarmClockhour[32];
char  AlarmClockmimu[32];
static void switch_event_handler(lv_event_t * e){
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * obj = lv_event_get_target(e);
    
    if (code == LV_EVENT_VALUE_CHANGED){
        // LV_UNUSED(obj);  
        switchState = lv_obj_has_state(obj, LV_STATE_CHECKED);
        // lv_dropdown_get_selected_str(ui_HourAlarm, AlarmClockhour,sizeof(AlarmClockhour));
        // lv_dropdown_get_selected_str(ui_MinuteAlarm,AlarmClockmimu,sizeof(AlarmClockmimu));
        
    }
}

static void ui_event_alarm_dropdown(lv_event_t * e) {
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * obj = lv_event_get_target(e);

    if(code == LV_EVENT_VALUE_CHANGED) {
        char buf[8];
        lv_dropdown_get_selected_str(obj, buf, sizeof(buf));
        
        // 逻辑处理：例如打印出当前选中的时间
        if(obj == ui_HourAlarm) {
            printf("Alarm Hour changed to: %s\n", buf);
            
            lv_dropdown_get_selected_str(ui_HourAlarm, AlarmClockhour,sizeof(AlarmClockhour));
            fal = 0;
        
        } else if(obj == ui_MinuteAlarm) {
            printf("Alarm Minute changed to: %s\n", buf);
            lv_dropdown_get_selected_str(ui_MinuteAlarm,AlarmClockmimu,sizeof(AlarmClockmimu));
            fal = 0;
        }
        
        // 如果需要立即保存闹钟时间，可以在这里调用你的闹钟设置逻辑
    }
}
// build funtions

void ui_AlarmClockScreen_screen_init(void)
{
    ui_AlarmClockScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AlarmClockScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AlarmClockScreen, lv_color_hex(0x26F7F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AlarmClockScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmClockLab = lv_label_create(ui_AlarmClockScreen);
    lv_obj_set_width(ui_AlarmClockLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AlarmClockLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmClockLab, 0);
    lv_obj_set_y(ui_AlarmClockLab, -100);
    lv_obj_set_align(ui_AlarmClockLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AlarmClockLab, "alarm clock");
    lv_obj_set_style_text_color(ui_AlarmClockLab, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AlarmClockLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HourAlarm = lv_dropdown_create(ui_AlarmClockScreen);
    lv_dropdown_set_dir(ui_HourAlarm, LV_DIR_RIGHT);
    lv_dropdown_set_options(ui_HourAlarm,
                            "\n0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23");
    lv_dropdown_set_selected_highlight(ui_HourAlarm, false);
    lv_obj_set_width(ui_HourAlarm, 50);
    lv_obj_set_height(ui_HourAlarm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HourAlarm, -45);
    lv_obj_set_y(ui_HourAlarm, -15);
    lv_obj_set_align(ui_HourAlarm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HourAlarm, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_MinuteAlarm = lv_dropdown_create(ui_AlarmClockScreen);
    lv_dropdown_set_dir(ui_MinuteAlarm, LV_DIR_LEFT);
    lv_dropdown_set_options(ui_MinuteAlarm,
                            "\n0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59");
    lv_obj_set_width(ui_MinuteAlarm, 50);
    lv_obj_set_height(ui_MinuteAlarm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MinuteAlarm, 45);
    lv_obj_set_y(ui_MinuteAlarm, -15);
    lv_obj_set_align(ui_MinuteAlarm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MinuteAlarm, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_HourAlarmLab = lv_label_create(ui_AlarmClockScreen);
    lv_obj_set_width(ui_HourAlarmLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HourAlarmLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HourAlarmLab, -45);
    lv_obj_set_y(ui_HourAlarmLab, -50);
    lv_obj_set_align(ui_HourAlarmLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HourAlarmLab, "Hour");

    ui_MinuteAlarmLab = lv_label_create(ui_AlarmClockScreen);
    lv_obj_set_width(ui_MinuteAlarmLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MinuteAlarmLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MinuteAlarmLab, 45);
    lv_obj_set_y(ui_MinuteAlarmLab, -50);
    lv_obj_set_align(ui_MinuteAlarmLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MinuteAlarmLab, "Minute");

    ui_AlarmClockSwitch = lv_switch_create(ui_AlarmClockScreen);
    lv_obj_set_width(ui_AlarmClockSwitch, 80);
    lv_obj_set_height(ui_AlarmClockSwitch, 40);
    lv_obj_set_x(ui_AlarmClockSwitch, 0);
    lv_obj_set_y(ui_AlarmClockSwitch, 70);
    lv_obj_set_align(ui_AlarmClockSwitch, LV_ALIGN_CENTER);

    
    ui_AlarmClockSwitchLab = lv_label_create(ui_AlarmClockScreen);
    lv_obj_set_width(ui_AlarmClockSwitchLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AlarmClockSwitchLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmClockSwitchLab, 0);
    lv_obj_set_y(ui_AlarmClockSwitchLab, 40);
    lv_obj_set_align(ui_AlarmClockSwitchLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AlarmClockSwitchLab, "OFF-ON");

    lv_obj_add_event_cb(ui_AlarmClockSwitch, switch_event_handler, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AlarmClockScreen, ui_event_AlarmClockScreen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HourAlarm, ui_event_alarm_dropdown, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_MinuteAlarm, ui_event_alarm_dropdown, LV_EVENT_VALUE_CHANGED, NULL);

}

void ui_AlarmClockScreen_screen_destroy(void)
{
    if(ui_AlarmClockScreen) lv_obj_del(ui_AlarmClockScreen);

    // NULL screen variables
    ui_AlarmClockScreen = NULL;
    ui_AlarmClockLab = NULL;
    ui_HourAlarm = NULL;
    ui_MinuteAlarm = NULL;
    ui_HourAlarmLab = NULL;
    ui_MinuteAlarmLab = NULL;
    ui_AlarmClockSwitch = NULL;
    ui_AlarmClockSwitchLab = NULL;

}
