// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ESP32S3Watch

#include "ui.h"


// event funtions

// build funtions

void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HomeScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeBackground = lv_img_create(ui_HomeScreen);
    lv_img_set_src(ui_HomeBackground, &ui_img_940840019);
    lv_obj_set_width(ui_HomeBackground, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_HomeBackground, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_HomeBackground, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeBackground, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeBackground, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmPm = lv_label_create(ui_HomeScreen);
    lv_obj_set_width( ui_AmPm, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_AmPm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_AmPm, 40 );
    lv_obj_set_y( ui_AmPm, -40 );
    lv_obj_set_align( ui_AmPm, LV_ALIGN_CENTER );
    lv_label_set_text(ui_AmPm,"AM");
    lv_obj_set_style_text_color(ui_AmPm, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_AmPm, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_MinuteHands = lv_img_create(ui_HomeScreen);
    lv_img_set_src(ui_MinuteHands, &ui_img_65333621);
    lv_obj_set_width(ui_MinuteHands, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_MinuteHands, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_MinuteHands, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MinuteHands, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MinuteHands, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_MinuteHands, 370);

    ui_Hourshands = lv_img_create(ui_HomeScreen);
    lv_img_set_src(ui_Hourshands, &ui_img_1547215259);
    lv_obj_set_width(ui_Hourshands, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_Hourshands, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Hourshands, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Hourshands, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Hourshands, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Hourshands, 120);

    ui_SecondHand = lv_img_create(ui_HomeScreen);
    lv_img_set_src(ui_SecondHand, &ui_img_1290532093);
    lv_obj_set_width(ui_SecondHand, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_SecondHand, LV_SIZE_CONTENT);    /// 230
    lv_obj_set_x(ui_SecondHand, 0);
    lv_obj_set_y(ui_SecondHand, 0);
    lv_obj_set_align(ui_SecondHand, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SecondHand, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SecondHand, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_add_event_cb(ui_HomeScreen, ui_event_HomeScreen, LV_EVENT_ALL, NULL);
    //lv_obj_add_event_cb(ui_HomeScreen, time_refresh, LV_EVENT_REFRESH, NULL);
    
}

void ui_HomeScreen_screen_destroy(void)
{
    if(ui_HomeScreen) lv_obj_del(ui_HomeScreen);

    // NULL screen variables
    ui_HomeScreen = NULL;
    ui_HomeBackground = NULL;
    ui_MinuteHands = NULL;
    ui_Hourshands = NULL;
    ui_SecondHand = NULL;

}
