// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ESP32S3Watch

#include "ui.h"


// event funtions

// build funtions

void ui_HomeScreen2_screen_init(void)
{
    ui_HomeScreen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomeScreen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HomeScreen2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeScreen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeScreen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeBackground2 = lv_img_create(ui_HomeScreen2);
    lv_img_set_src(ui_HomeBackground2, &ui_img_1668922148);
    lv_obj_set_width(ui_HomeBackground2, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_HomeBackground2, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_HomeBackground2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeBackground2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeBackground2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmPm2 = lv_label_create(ui_HomeScreen2);
    lv_obj_set_width( ui_AmPm2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_AmPm2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_AmPm2, 40 );
    lv_obj_set_y( ui_AmPm2, -40 );
    lv_obj_set_align( ui_AmPm2, LV_ALIGN_CENTER );
    lv_label_set_text(ui_AmPm2,"AM");
    lv_obj_set_style_text_color(ui_AmPm2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_AmPm2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_Hourshands2 = lv_img_create(ui_HomeScreen2);
    lv_img_set_src(ui_Hourshands2, &ui_img_1666022858);
    lv_obj_set_width(ui_Hourshands2, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_Hourshands2, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Hourshands2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Hourshands2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Hourshands2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MinuteHands2 = lv_img_create(ui_HomeScreen2);
    lv_img_set_src(ui_MinuteHands2, &ui_img_1016395558);
    lv_obj_set_width(ui_MinuteHands2, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_MinuteHands2, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_MinuteHands2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MinuteHands2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MinuteHands2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SecondHand1 = lv_img_create(ui_HomeScreen2);
    lv_img_set_src(ui_SecondHand1, &ui_img_1290539516);
    lv_obj_set_width(ui_SecondHand1, LV_SIZE_CONTENT);   /// 480
    lv_obj_set_height(ui_SecondHand1, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_SecondHand1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SecondHand1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SecondHand1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_HomeScreen2, ui_event_HomeScreen2, LV_EVENT_ALL, NULL);

}

void ui_HomeScreen2_screen_destroy(void)
{
    if(ui_HomeScreen2) lv_obj_del(ui_HomeScreen2);

    // NULL screen variables
    ui_HomeScreen2 = NULL;
    ui_HomeBackground2 = NULL;
    ui_Hourshands2 = NULL;
    ui_MinuteHands2 = NULL;
    ui_SecondHand1 = NULL;

}
