// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ESP32S3Watch

#include "ui.h"

// event funtions

// build funtions

void ui_SplashScreen_screen_init(void)
{
    ui_SplashScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SplashScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SplashScreen, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SplashScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SplashScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackgroundPic = lv_img_create(ui_SplashScreen);
    lv_img_set_src(ui_BackgroundPic, &ui_img_bj_02_png);
    lv_obj_set_width(ui_BackgroundPic, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_BackgroundPic, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_BackgroundPic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackgroundPic, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BackgroundPic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_logo = lv_img_create(ui_SplashScreen);
    lv_img_set_src(ui_logo, &ui_img_1689836819);
    lv_obj_set_width(ui_logo, LV_SIZE_CONTENT);   /// 68
    lv_obj_set_height(ui_logo, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_align(ui_logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_SplashScreen, ui_event_SplashScreen, LV_EVENT_ALL, NULL);
}

void ui_SplashScreen_screen_destroy(void)
{
    if(ui_SplashScreen) lv_obj_del(ui_SplashScreen);

    // NULL screen variables
    ui_SplashScreen = NULL;
    ui_BackgroundPic = NULL;
    ui_logo = NULL;

}
