// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ESP32S3Watch

#ifndef UI_SPLASHSCREEN_H
#define UI_SPLASHSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SplashScreen
extern void ui_SplashScreen_screen_init(void);
extern void ui_SplashScreen_screen_destroy(void);
extern lv_obj_t * ui_SplashScreen;
extern lv_obj_t * ui_BackgroundPic;
extern lv_obj_t * ui_logo;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

