// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ESP32S3Watch

#include "ui.h"

lv_obj_t * ui_testscreen = NULL;
// event funtions

// build funtions

void ui_testscreen_screen_init(void)
{
    ui_testscreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_testscreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_testscreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_testscreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_testscreen_screen_destroy(void)
{
    if(ui_testscreen) lv_obj_del(ui_testscreen);

    // NULL screen variables
    ui_testscreen = NULL;

}
