// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ESP32S3Watch

#ifndef UI_TESTSCREEN_H
#define UI_TESTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_testscreen
extern void ui_testscreen_screen_init(void);
extern void ui_testscreen_screen_destroy(void);
extern lv_obj_t * ui_testscreen;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

